### ISSUE TITLE
Typo in documented content type

### ISSUE THREAD

**Issue by nbibler** [robertodecurnex/rack-jsonp-middleware#1]
See https://github.com/robertodecurnex/rack-jsonp-middleware/blob/gh-pages/index.html#L125

It should be "application" rather than "aplication"

**Comment by robertodecurnex** [comment]
Fixing aplication typo; Closed by d7ab2f567924ad8944be656b169d70c8ae9ef2bb

**Comment by robertodecurnex** [comment]
Thank you Nate!
