### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by chrisjpowers** [robertodecurnex/rack-jsonp-middleware#10]
I believe this line:

> But http://domain.com/action.json?callback=J50Npi.sucess will still return:

should read:

> But http://domain.com/action.json will still return:

**Comment by chrisjpowers** [comment]
Oh, nevermind, now I see one is .json and the other is .jsonp

**Comment by robertodecurnex** [comment]
Exactly, I have added that example since it's one of the main differences between this and the rack-contrib middle-ware. 

The existence of the callback param do not imply the usage of jsonp.

Your intention is appreciated anyway ;) 

Thank you!
