### ISSUE TITLE
Authenticity token in JSONP request

### ISSUE THREAD

**Issue by romanoff** [robertodecurnex/rack-jsonp-middleware#2]
Your gem works great. But I may want to use jsonp service internally only (application with lots of javascript functionality). In this case authenticity_token may be required for certain controllers. (So, /user_info.jsonp?callback=user_info won't work. But  /user_info.jsonp?callback=user_info&authenticity_token=<authenticity_token>). Didn't you think about such functionality?

**Comment by robertodecurnex** [comment]
Are you facing any specific problem? 
You should be able to pass any param that you want and manage the request as you normally do. 
Not sure why should I care about the authenticity_token here. It should not be responsibility of this piece of middleware.
Please let me know if I'm missing something or I'm not getting your point right.

**Comment by romanoff** [comment]
Well, generally I may want to access JSONP service only from my website and not to allow others use it. (if user will be logged in on my website, entering website with different domain name, this user can share his information through JSONP service. But I may not want this ). But probably the code I want should be embedded not on the middleware level.
