### ISSUE TITLE
Content-Type String is directly modified

### ISSUE THREAD

**Issue by joelmats** [robertodecurnex/rack-jsonp-middleware#8]
I ran into a problem when using this along side Grape API due to the fact that the string is modified using "sub!" instead of just assigning it and using "sub". This inadvertently modified a "constant" being used in grape.

I fixed it by modifying line 31 in jsonp.rb to:

``` ruby
headers['Content-Type'] = headers['Content-Type'].sub(/^[^;]+(;?)/, "#{MIME_TYPE}\\1")
```

**Comment by robertodecurnex** [comment]
Thank you! I'll include that change soon so we can live along side Grape without problems.
